# Generated by Django 4.2 on 2023-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='plugins',
        ),
    ]
