# Generated by Django 4.2 on 2023-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='extension',
            field=models.CharField(blank=True, max_length=18, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='files',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='weight'),
        ),
    ]
