# Generated by Django 4.2 on 2023-04-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_files_extension_alter_files_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='user',
            new_name='email',
        ),
    ]
