# Generated by Django 4.2 on 2023-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_files_extension_remove_files_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='file'),
        ),
    ]
