# Generated by Django 4.2 on 2023-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_files_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('weight', models.IntegerField(blank=True, verbose_name='weight')),
                ('extension', models.CharField(blank=True, max_length=18, verbose_name='extension')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='date')),
            ],
        ),
    ]
