# Generated by Django 4.2 on 2023-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_filesinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to='files', verbose_name='file'),
        ),
    ]
