# Generated by Django 4.2 on 2023-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
