# Generated by Django 4.2 on 2023-04-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_files_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='name',
            new_name='link',
        ),
    ]
